services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $fontawesomeStyles: '%markocupic_fontawesome_icon_picker.fontawesome_styles%'

  Markocupic\ServiceLinkBundle\:
    resource: ../src/
    exclude: ../../{DependencyInjection,Model}

